### ISSUE TITLE
How to get user's Xbox Live Profile information?

### ISSUE THREAD

**Issue by EvanEvan-17** [AlphaBs/XboxAuthNet#1]
I have a Minecraft Launcher which use CmlLib.Core library and this library as a dependency. I want to ask how to get user's Xbox Live Profile information after getting a token? Actually I already know that thing but there is a problem. So the flow is: get the user's xsts token for Xbox Live, send it to my API server with the XUID (as the current API endpoint need XUID). The problem is that if the user's know other user's Xbox UID, then they can impersonate as other Xbox account and get a private information which stored on my server. I have tried to call Xbox Live Profile API with my primary Xbox Account token and then I use the XUID of my OTHER Xbox Account, and it worked! That's danger, because impersonation to my API server is possible because of that.

**Comment by AlphaBs** [comment]
sorry I don't know how to get xbox live profile information. I don't know what api is used to get user's profile

**Comment by EvanEvan-17** [comment]
I've fixed this issue myself!
