### ISSUE TITLE
So how does this work?

### ISSUE THREAD

**Issue by NextLVLHasH** [AlphaBs/XboxAuthNet#9]
im wondering how does this work and can it generate a xbox one token?

**Comment by AlphaBs** [comment]
This library implements [Microsoft OAuth code flow](https://learn.microsoft.com/en-us/entra/identity-platform/v2-oauth2-auth-code-flow) and some Xbox Authentication APIs. 

it is originally developed for authentication for Xbox games like Minecraft. you can get xsts token if you know `relyingParty` of the game and also some Xbox profile information.
